name: Auto Create Pull Request

on:
  schedule:
    - cron: '5 12 * * *'  # Runs daily at 12:05 PM UTC
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Supriya"
          git config --global user.email "supriyasrivastava2004@gmail.com"

      - name: Add Upstream & Sync Fork
        run: |
          git remote add upstream https://github.com/AliceWonderland/hacktoberfest.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit

      - name: Delete Old Sync Branch (If Exists)
        continue-on-error: true
        run: |
          git branch -D sync-branch || true
          git push origin --delete sync-branch || true

      - name: Create Sync Branch
        run: |
          git checkout -b sync-branch
          git push origin sync-branch --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto-Synced PR"
          body: "This PR syncs my fork with the latest updates from upstream."
          branch: "sync-branch"
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
